site_name: docs
site_url: https://guntas-13.github.io/osl.docs
site_author: Guntas Singh Saran

repo_name: mshandilya/osl.
repo_url: https://github.com/mshandilya/osl.

copyright: Copyright &copy; 2025 - 2026 Guntas Singh Saran | Kishan Ved | Kristopher Paul | Mrigankashekhar Shandilya

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/guntas-13
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/guntas-singh-saran-2b8811179/
    - icon: fontawesome/brands/discord
      link: https://www.discord.com/users/1025808683382345768
    - icon: fontawesome/solid/paper-plane
      link: mailto:guntassingh.saran@iitgn.ac.in
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Love the UnAmbiguity?
      ratings:
        - icon: material/heart
          name: loved it!
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: It could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve it by
            writing to <a href="mailto:guntassingh.saran@iitgn.ac.in" target="_blank" rel="noopener">guntassingh.saran@iitgn.ac.in</a>.

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # - navigation.footer
  logo: assets/oslNameLogo.svg
  favicon: assets/oslMascotLogo.svg
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Poppins
    code: JetBrains Mono

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.blocks.caption
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started: gettingstarted/gs.md
  - Documentation:
      - Variables & Constants: documentation/variables.md
      - Functions: documentation/func.md
      - Syntax: documentation/syn.md
      - Features: documentation/features.md
      - Grammar: documentation/grammar.md
  - Developer Guide:
      - Abstract Syntax: dev/ast_nodes.md
      - Bytecode: dev/bytecodeLeg.md
      - Escape Analysis: dev/escape.md
      - Virtual Machine: dev/VM.md
      - Garbage Collection: dev/gc.md
      - Lexer and Parser Generator: dev/gen.md
      - Contributing: dev/contribute.md
  - Tutorials:
      - Euler Problems: tutorials/euler.md
      - ByteCode Generation: tutorials/byteEx.md
      - Low-Level Compiler: tutorials/cpp.md
  # - Issues: issues/issues.md
  # - Progress:
  #     - Home: progress/progress.md
  #     - Week 1: progress/week1.md
  #     - Week 2: progress/week2.md

extra_css:
  - stylesheets/extra.css
